#!/usr/bin/env python3
# Copyright 2026 Mozkey contributors.
#
# Generates the compact C++ word table used by EnglishWordDictionaryRewriter.
# Input files are plain word lists generated by ESDB/SCOWL. Earlier (smaller)
# ESDB sizes are treated as higher-priority tiers.

from __future__ import annotations

import argparse
import pathlib
import re
from typing import Dict

_WORD_RE = re.compile(r"^[A-Za-z]+(?:['-][A-Za-z]+)*$")
_MAX_WORD_LENGTH = 40


def _parse_tier_arg(value: str) -> tuple[int, pathlib.Path]:
    tier_text, separator, path_text = value.partition("=")
    if not separator:
        raise argparse.ArgumentTypeError("expected TIER=PATH")
    try:
        tier = int(tier_text)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("TIER must be an integer") from exc
    if not 0 <= tier <= 255:
        raise argparse.ArgumentTypeError("TIER must fit uint8")
    return tier, pathlib.Path(path_text)


def _read_word_list(path: pathlib.Path, tier: int, words: Dict[str, int]) -> None:
    with path.open("r", encoding="utf-8") as source:
        for raw_line in source:
            word = raw_line.strip()
            if not word or len(word) > _MAX_WORD_LENGTH:
                continue
            if not _WORD_RE.fullmatch(word):
                continue
            key = word.lower()
            previous = words.get(key)
            if previous is None or tier < previous:
                words[key] = tier


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--tier-list",
        action="append",
        required=True,
        type=_parse_tier_arg,
        metavar="TIER=PATH",
        help="ESDB word list and the priority tier assigned to its words",
    )
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--source-revision", default="unknown")
    args = parser.parse_args()

    words: Dict[str, int] = {}
    for tier, path in sorted(args.tier_list, key=lambda item: item[0]):
        _read_word_list(path, tier, words)

    rows = sorted(words.items())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write("// Generated file. Do not edit manually.\n")
        output.write("// Source: ESDB/SCOWL (en-wl/wordlist)\n")
        output.write(f"// Source revision: {args.source_revision}\n")
        output.write(f"// Entries: {len(rows)}\n")
        output.write("constexpr EnglishWordData kEnglishWordDictionary[] = {\n")
        for word, tier in rows:
            output.write(f'    {{"{word}", {tier}}},\n')
        output.write("};\n")

    print(f"generated {len(rows)} English words -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
